# Generated by Django 4.2.2 on 2023-07-21 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_screenshots_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(related_name='screenshots_games', to='games.screenshots', verbose_name='скриншоты'),
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 21, 9, 4, 133747), verbose_name='дата истечения'),
        ),
    ]
